#!/usr/bin/env python3
import os
import csv
import random
import re
from collections import defaultdict

# Core Configuration
GB_FILE = "KX894508.gb"
ITERATIONS = 10000

def parse_genbank_spaces(gb_path):
    """Parses GenBank to extract precise baseline sizes for Genic and Intergenic spaces."""
    if not os.path.exists(gb_path):
        raise FileNotFoundError(f"Missing required GenBank reference genome file: {gb_path}")
        
    origin_seq = []
    in_origin = False
    genic_indices = set()
    
    with open(gb_path, 'r') as f:
        for line in f:
            if line.startswith("ORIGIN"):
                in_origin = True
                continue
            if in_origin:
                clean_seq = "".join(c for c in line.strip() if c.isalpha())
                if clean_seq:
                    origin_seq.append(clean_seq.upper())
                continue
                
            if line.startswith("     CDS             "):
                match = re.findall(r'\d+', line.strip())
                if match and len(match) >= 2:
                    start, end = int(match[0]), int(match[1])
                    for pos in range(start - 1, end):
                        genic_indices.add(pos)
                        
    full_genome = "".join(origin_seq)
    total_size = len(full_genome)
    genic_size = len(genic_indices)
    intergenic_size = total_size - genic_size
    return genic_size, intergenic_size

def load_detailed_mutations(taxon_key):
    """Loads mutations from the detailed CSV files generated by the primary analysis script."""
    filename = f"{taxon_key}_detailed_mutations.csv"
    mutations = {}
    if not os.path.exists(filename):
        print(f"Warning: Expected file {filename} not found. Skipping lineage.")
        return mutations
        
    with open(filename, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Filter out low quality/incomplete contexts
            if row['Mutation_Type'] == 'Incomplete_Codon_Context':
                continue
            pos = int(row['Genome_Position'])
            mutations[pos] = {
                'mut_type': row['Mutation_Type'],
                'derived_nt': row[f"{taxon_key}_Base_CDS"] if f"{taxon_key}_Base_CDS" in row else row['CaPV_Base_CDS'],
                'derived_aa': row[f"{taxon_key}_AA"] if f"{taxon_key}_AA" in row else row['CaPV_AA']
            }
    return mutations

def execution_context():
    print("========================================================================")
    print("          CAPRIPOXVIRUS CATEGORY-STRATIFIED PERMUTATION ENGINE          ")
    print("========================================================================")
    
    # 1. Establish structural baseline dimensions
    print("Extracting genomic landscape partitions from GenBank...")
    genic_space, intergenic_space = parse_genbank_spaces(GB_FILE)
    print(f"--> Coding (Genic) Space Baseline:     {genic_space} bp")
    print(f"--> Non-coding (Intergenic) Baseline:  {intergenic_space} bp\n")
    
    # 2. Extract parsed tracking arrays
    taxa = ["LSDV", "SPPV", "SPPV_modern", "GTPV"]
    mutation_data = {}
    for t in taxa:
        mutation_data[t] = load_detailed_mutations(t)
        
    sppv_anc = mutation_data.get("SPPV", {})
    
    pairs = [
        ("LSDV", "SPPV"), ("LSDV", "SPPV_modern"), ("LSDV", "GTPV"), 
        ("GTPV", "SPPV"), ("GTPV", "SPPV_modern")
    ]
    
    categories = ["Intergenic", "Synonymous", "Nonsynonymous"]
    
    # Gather testing matrix items
    test_tasks = []
    
    for t1, t2 in pairs:
        muts1 = mutation_data[t1]
        muts2 = mutation_data[t2]
        
        # Isolate clean analysis targets, respecting historical ancestral filters
        clean_muts1 = {}
        for pos, m in muts1.items():
            if t1 == "SPPV_modern" and pos in sppv_anc and sppv_anc[pos]['derived_nt'] == m['derived_nt']:
                continue
            clean_muts1[pos] = m
            
        clean_muts2 = {}
        for pos, m in muts2.items():
            if t2 == "SPPV_modern" and pos in sppv_anc and sppv_anc[pos]['derived_nt'] == m['derived_nt']:
                continue
            clean_muts2[pos] = m
            
        for cat in categories:
            # Filter vectors corresponding directly to category constraints
            p1_pool = [m for m in clean_muts1.values() if m['mut_type'] == cat]
            p2_pool = [m for m in clean_muts2.values() if m['mut_type'] == cat]
            
            # Count precise observed occurrences matching your stringent criteria
            obs_count = 0
            shared_positions = set(clean_muts1.keys()) & set(clean_muts2.keys())
            for pos in shared_positions:
                m1 = clean_muts1[pos]
                m2 = clean_muts2[pos]
                if m1['mut_type'] == cat and m2['mut_type'] == cat:
                    if cat in ['Intergenic', 'Synonymous']:
                        if m1['derived_nt'] == m2['derived_nt']:
                            obs_count += 1
                    elif cat == 'Nonsynonymous':
                        if m1['derived_aa'] == m2['derived_aa']:
                            obs_count += 1
                            
            test_tasks.append({
                'pair': f"{t1} vs {t2}",
                'category': cat,
                'pool1': p1_pool,
                'pool2': p2_pool,
                'observed': obs_count,
                'bound_space': intergenic_space if cat == "Intergenic" else genic_space
            })

    print(f"Running background spatial shuffling permutations ({ITERATIONS} iterations)...")
    
    # Run simulation iterations
    for task in test_tasks:
        cat = task['category']
        space_limit = task['bound_space']
        p1 = task['pool1']
        p2 = task['pool2']
        obs = task['observed']
        
        sim_counts = []
        
        for _ in range(ITERATIONS):
            # Uniform random sampling across structural boundaries
            r_pos1 = random.sample(range(1, space_limit + 1), len(p1))
            r_pos2 = random.sample(range(1, space_limit + 1), len(p2))
            
            sim1 = dict(zip(r_pos1, p1))
            sim2 = dict(zip(r_pos2, p2))
            
            sim_shared = 0
            overlapping_hits = set(sim1.keys()) & set(sim2.keys())
            
            for p in overlapping_hits:
                if cat in ['Intergenic', 'Synonymous']:
                    if sim1[p]['derived_nt'] == sim2[p]['derived_nt']:
                        sim_shared += 1
                elif cat == 'Nonsynonymous':
                    if sim1[p]['derived_aa'] == sim2[p]['derived_aa']:
                        sim_shared += 1
                        
            sim_counts.append(sim_shared)
            
        task['expected'] = sum(sim_counts) / ITERATIONS
        # Strict exact precision mapping without truncation rounding adjustments
        task['raw_p'] = sum(1 for c in sim_counts if c >= obs) / ITERATIONS

    # 3. Apply Benjamini-Hochberg False Discovery Rate adjustment across the matrix
    m = len(test_tasks)
    sorted_tasks = sorted(enumerate(test_tasks), key=lambda x: x[1]['raw_p'])
    
    prev_adj = 1.0
    for rank, (orig_idx, task) in reversed(list(enumerate(sorted_tasks, start=1))):
        adj_p = min(task['raw_p'] * m / rank, prev_adj, 1.0)
        test_tasks[orig_idx]['adj_p'] = adj_p
        prev_adj = adj_p

    # 4. Generate structured analytical metrics report
    output_csv = "category_permutation_results.csv"
    with open(output_csv, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["Comparison_Pair", "Functional_Category", "Observed_Shared_SNPs", "Expected_Shared_SNPs", "Raw_P_Value", "BH_Adj_P_Value"])
        for task in test_tasks:
            writer.writerow([task['pair'], task['category'], task['observed'], f"{task['expected']:.4f}", repr(task['raw_p']), repr(task['adj_p'])])

    print(f"\nSimulation complete. Results written directly to: {output_csv}\n")
    print(f"{'Comparison Pair':<22} | {'Category':<15} | {'Observed':<8} | {'Expected':<10} | {'Raw P-Value':<20} | {'BH Adj P-Value':<20}")
    print("-" * 105)
    for task in test_tasks:
        # Utilizing explicit raw float representations to avoid rounding masks
        print(f"{task['pair']:<22} | {task['category']:<15} | {task['observed']:<8} | {task['expected']:<10.4f} | {repr(task['raw_p']):<20} | {repr(task['adj_p']):<20}")

if __name__ == "__main__":
    execution_context()
